### ISSUE TITLE
[Feature] Host groups

### ISSUE THREAD

**Issue by theblazehen** [ducted/duct#11]
Support passing in a list of sources to use to a list of hosts

**Comment by calston** [comment]
I've yet to implement any actual code, but I documented the idea I had for this here 

https://github.com/ducted/duct/blob/feature/easier_configuration/docs/blueprints.rst

Any comments / suggestions 

+ @jerith

**Comment by jerith** [comment]
It would be really helpful if we could split the config (especially for sources) into multiple included files.

This would make it possible to structure puppet (or any other config management system) modules in a way that keeps Duct source configs near the services they're monitoring and avoid having to separately specify metric collection per-host.

**Comment by calston** [comment]
You can already do that with the `include_path` option, this is a bit poorly documented however. It might help if it's something a bit more logical like `include: /foo/bar.yaml` which could also accept a wildcard syntax. The new config parser at least extends it to accept a list of paths wherein it will search for any `.yml` or `.yaml` extension.
