### ISSUE TITLE
Report available memory for systems that support it

### ISSUE THREAD

**Issue by jerith** [ducted/duct#15]
Newer linux kernels report `MemAvailable` in `/proc/meminfo` (see the relevant section of https://www.kernel.org/doc/Documentation/filesystems/proc.txt for details).

This is a much more useful metric to monitor and alert on than `MemFree`, because it accounts for things like XFS inode caches which are reclaimable but aren't considered free.

**Comment by calston** [comment]
Nice one, thanks
